version: "3.8"
services:
  musicbot:
    build: .
    command: python src/main.py
    volumes:
      - ./src:/app/src
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN} 
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - redis

  redis:
    image: redis:latest